PR - Fixes Issue #34
ImaginaryDevelopment/imaginary-hero-designer pull request #44
Opened 2019-07-17 20:12 UTC by Crytilis

This PR fixes issue #34
Updated assembly name and icons
Added support for exporting to discord.

2019-07-17 20:38 UTC, ImaginaryDevelopment requested changes
almost there

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/packages.config
> +  <package id="Nancy" version="2.0.0" targetFramework="net472" />
Is this being used?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Hero Designer.csproj
> +    <Reference Include="Nancy, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
There's another serializer right below this.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Hero Designer.csproj
> -    <AssemblyName>Hero Designer</AssemblyName>
This may be a problem for leaving orphaned file associations, Also I think some code may be dependent upon the exact name. Let me see.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/frmMain.cs
> +            new Clshook().MainAsync();
perhaps the class could be adjusted to not require an instance if you have no reason to hold on to it? also, no try/catch inside an event handler will bring the app down on failure.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (dcChannel.Text != string.Empty)
shouldn't this be `!string.IsNullOrEmpty(dcChannel.Text)` and/or checking for not whitespace?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (dcNickName.Text != string.Empty)
shouldn't this be `!string.IsNullOrEmpty(dcChannel.Text)` and/or checking for not whitespace?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox3.Text = "More Discord settings may be available\nin the future.";
Why a richTextBox to display a single string?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Base/ConfigData.cs
> +                this.DNickName = reader.ReadString();
we aren't writing out config to a `.mhd` file any longer, so trying to read them from one is just added code that could break migrations from older configs.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox2.BackColor = System.Drawing.SystemColors.Window;
another RichTextBox for a single line of text, without any special rich coloring.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox1.BackColor = System.Drawing.SystemColors.Window;
RichTextBox, justified?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +        {
would prefer `=>` for single statement methods

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            var dcAddServer = dcServerName.Text;
I don't think the variable needs a name, just to be passed later.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (MidsContext.Config.DSelServer == dcSelectedItem.ToString())
should we account for the possibility of null here? `.ToString()` might throw

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +                _ = MidsContext.Config.DSelServer == String.Empty;
is this variable `_` truly unused? remove if not, rename if so. why is there a branch that does nothing?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/clsHook.cs
> +            var objWebRequest = (HttpWebRequest) WebRequest.Create(URL);
pretty sure these should be making use of `using(...` clauses

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/clsHook.cs
> +            var discordserver = MidsContext.Config.DSelServer.Replace(" (Default)", "");
lots of variables get created, and initialized, only to be used, never changed. should be able to inline them so we only have to look at the variables that actually vary.

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/clsHook.cs
> +            Thread.Sleep(1000);
is this justified? Sleep why?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/clsHook.cs
> +            var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://hooks.midsreborn.com:3000/api?token=UmQhT4kDrS0gA5MF5aGli8zbYCUmQhT4kDrS0gA5MF5aGli8zbYC");
is this ok to be here in plain text?

2019-07-17 20:38 UTC, ImaginaryDevelopment commented on Hero Designer/clsHook.cs
> +            Thread.Sleep(1000);
Why so sleepy?

2019-07-17 21:37 UTC, Crytilis commented on Hero Designer/Hero Designer.csproj
> -    <AssemblyName>Hero Designer</AssemblyName>
Changed the Assembly name back to Hero Designer, once I finish other changes I will push.

2019-07-17 21:39 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (dcChannel.Text != string.Empty)
Good point, I'll make this change.

2019-07-17 21:40 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox3.Text = "More Discord settings may be available\nin the future.";
It originally wasn't as single string so I used a richtextbox instead of a label and never bothered to change it when I redid it.

2019-07-17 21:41 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox2.BackColor = System.Drawing.SystemColors.Window;
I could color it, I just dislike labels for the most part.

2019-07-18 02:02 UTC, Crytilis commented on Hero Designer/clsHook.cs
> +            Thread.Sleep(1000);
Removed

2019-07-18 02:02 UTC, Crytilis commented on Hero Designer/clsHook.cs
> +            var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://hooks.midsreborn.com:3000/api?token=UmQhT4kDrS0gA5MF5aGli8zbYCUmQhT4kDrS0gA5MF5aGli8zbYC");
Changed to base64 string

2019-07-18 02:02 UTC, Crytilis commented on Hero Designer/clsHook.cs
> +            Thread.Sleep(1000);
removed

2019-07-18 02:02 UTC, Crytilis commented on Hero Designer/clsHook.cs
> +            var discordserver = MidsContext.Config.DSelServer.Replace(" (Default)", "");
Variables condensed

2019-07-18 02:03 UTC, Crytilis commented on Hero Designer/clsHook.cs
> +            var objWebRequest = (HttpWebRequest) WebRequest.Create(URL);
change to using

2019-07-18 02:03 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +                _ = MidsContext.Config.DSelServer == String.Empty;
Modified

2019-07-18 02:03 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (MidsContext.Config.DSelServer == dcSelectedItem.ToString())
Null possibility accounted for

2019-07-18 02:03 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            var dcAddServer = dcServerName.Text;
var removed

2019-07-18 02:03 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +        {
changed

2019-07-18 02:04 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.Designer.cs
> +            this.richTextBox1.BackColor = System.Drawing.SystemColors.Window;
I just prefer richtext in case we want to change and color later without modifying the control

2019-07-18 02:06 UTC, Crytilis commented on Base/ConfigData.cs
> +                this.DNickName = reader.ReadString();
commented this portion out, ill remove it later.

2019-07-18 02:06 UTC, Crytilis commented on Hero Designer/Forms/OptionsMenuItems/frmCalcOpt.cs
> +            if (dcNickName.Text != string.Empty)
changed

2019-07-18 02:06 UTC, Crytilis commented on Hero Designer/Forms/frmMain.cs
> +            new Clshook().MainAsync();
changed and included try/catch

2019-07-18 02:07 UTC, Crytilis commented on Hero Designer/Hero Designer.csproj
> +    <Reference Include="Nancy, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
removed nancy and used json.net from newton since we already have

2019-07-18 02:07 UTC, Crytilis commented on Hero Designer/packages.config
> +  <package id="Nancy" version="2.0.0" targetFramework="net472" />
removed

2019-07-18 14:37 UTC, ImaginaryDevelopment approved these changes

2019-07-18 14:37 UTC, ImaginaryDevelopment commented on Base/ConfigData.cs
> +                this.DNickName = reader.ReadString();
Not sure if it is github or what, but this still shows as being present

2019-07-18 14:47 UTC, ImaginaryDevelopment approved these changes
Why are so many designers changed? is this a simple consequence of changing the icons?

2019-07-18 14:47 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/ImportExportItems/frmExportColor.Designer.cs
> +using System.Drawing;
This file looks hand-edited, is that the case?

2019-07-18 14:47 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/ImportExportItems/frmImportEffects.Designer.cs
> +            this.Controls.Add(this.HideUnchanged);
This also looks hand-edited.

2019-07-18 14:47 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/ImportExportItems/frmImportPowerLevels.Designer.cs
> +            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
This line used to be in nearly all the forms, but was crashing the designer, does it work now?

2019-07-18 14:47 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/ImportExportItems/frmImport_Archetype.Designer.cs
> +            this.Controls.Add(this.btnClose);
This looks hand-edited, please confirm it still loads in designer.

2019-07-18 14:50 UTC, Crytilis commented on Hero Designer/Forms/ImportExportItems/frmExportColor.Designer.cs
> +using System.Drawing;
Nope, didn't hand edit it. I removed the Icon and added it back the correct way.

2019-07-18 14:50 UTC, Crytilis commented on Hero Designer/Forms/ImportExportItems/frmImportEffects.Designer.cs
> +            this.Controls.Add(this.HideUnchanged);
Wasn't

2019-07-18 14:51 UTC, Crytilis commented on Hero Designer/Forms/ImportExportItems/frmImportPowerLevels.Designer.cs
> +            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
I didn't change all the forms Icons yet, just some of them. That is the line where it was done by hand rather than letting VS do it as you should.

2019-07-18 14:52 UTC, ImaginaryDevelopment commented on Hero Designer/Forms/ImportExportItems/frmImportPowerLevels.Designer.cs
> +            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
So I'm not clear on this, You added this line by hand, or no?

2019-07-18 14:55 UTC, merged